lang: en-US
title: zudoku
email: zudoku@jfs.sh
description: Intuitive Zero-Knowledge Primer.
baseurl: ""
url: "https://zudoku.xyz"

# Author information
author:
  name: Jan Ferdinand Sauer
  url: "https://jfs.sh"

# Build settings
remote_theme: mmistakes/jekyll-theme-basically-basic@1.4.5

# custom footer (hackish)
copyright: '[![CC BY 4.0](assets/pic/cc_by.svg)](https://creativecommons.org/licenses/by/4.0/) \|
    made with ü§ç by [jfs](jfs.sh) \|
    üíå [feedback](mailto:zudoku@jfs.sh) \|
    ![github](assets/pic/github_mark.svg) [improve this page](https://github.com/42ndTowel/zudoku)'